# Header
menu:
  Sobre: sobre
  Newsletter: http://eepurl.com/bpmluL
  Github:
    url: https://github.com/dorianneto
    icon: github
  Twitter:
    url: https://twitter.com/doriansneto
    icon: twitter
  Linkedin:
    url: https://www.linkedin.com/in/dorianneto
    icon: linkedin

# Title on top left of menu. Leave empty to use main blog title
menu_title: home

# URL of the Home page image
index_cover: /assets/img/bg-cover.jpg

# Default post title
default_post_title: Sem título

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: dorianneto
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-58753308-1

# Addthis ID
addthis: ra-54c1374b3b5ec2f9

# Social Accounts
twitter_url: https://twitter.com/doriansneto
facebook_url: https://www.facebook.com/doriansampaioneto
github_url: https://github.com/dorianneto
linkedin_url: https://www.linkedin.com/in/dorianneto
mailto: doriansampaioneto@gmail.com